# Enable HPPS SMC-353 memory controller hardware and configure HPPS DRAM of
# 128MB size in Qemu. Preload TRCH SSW Bare-Metal App binary (configured with
# minimal feature set) into TRCH SRAM, and load a bare-metal image into HPPS
# DRAM by HW emulator (fast).

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-bm/Makefile
include $(CONF)/lib-hpps-smc/Makefile
