# Like sys-preload-trch-bm-min-hpps-128M-ub-nodcd-booti-busybox, but
# with HPPS A53 both clusters (8 processors total) enabled in Qemu, and Linux
# configured to boot in SMP mode.

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-ub-nodcd-booti-busybox/Makefile
include $(CONF)/lib-hpps-linux-smp8/Makefile
