# Like sys-preload-trch-bm-min-hpps-128M-atf-sev-ub-nodcd-booti-busybox but
# with Synopsys DWC QoS Ethernet NIC model enabled in Qemu and with drivers
# configured in Linux.

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-atf-sev-ub-nodcd-booti-busybox/Makefile
include $(CONF)/lib-hpps-eth-snps/Makefile
