# Enable the MTD subsystem in HPPS Linux

$(call push-prof)
# includes
PROF_CONF:=$(CONF)/$(call pop-prof)

$(PROF_BLD)/hpps/linux.config: $(PROF_CONF)/hpps/linux.config
$(PROF_BLD)/hpps/busybox.miniconf: $(PROF_CONF)/hpps/busybox.miniconf
