# Like sys-preload-trch-bm-min-hpps-128M-atf-sev-booti-busybox, but with the
# workaround for the hang in U-boot upon Dcache disable (do not disable).

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-atf-sev-booti-busybox/Makefile
include $(CONF)/lib-hpps-uboot-nodcd/Makefile
