# Set the NOTIFIER as the default watchdog pre-timeout governor.
# HPSC kernel monitor handles the notifications.

$(call push-prof)
# includes
PROF_CONF:=$(CONF)/$(call pop-prof)

$(PROF_BLD)/hpps/linux.config: $(PROF_CONF)/hpps/linux.config
