# Like sys-preload-trch-bm-min-hpps-128M-ub-nodcd-dbg-booti-busybox, but
# with ATF workaround that disables dual-issue feature in Cortex-A53.

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-ub-nodcd-dbg-booti-busybox/Makefile
include $(CONF)/lib-hpps-atf-si/Makefile
