# Like sys-preload-trch-bm-min-hpps-128M-atf-sev-ub-nodcd-booti-busybox, but
# with HPPS A53 cluster 0 of 4 processors enabled in Qemu, and Linux configured
# to boot in SMP mode.

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-atf-sev-ub-nodcd-booti-busybox/Makefile
include $(CONF)/lib-hpps-linux-smp4/Makefile
