# Like sys-preload-trch-bm-min-hpps-128M-ub-nodcd-booti-busybox, but
# with some debug output in U-boot enabled.

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-ub-nodcd-booti-busybox/Makefile
include $(CONF)/lib-hpps-uboot-dbg/Makefile
