# Like sys-preload-trch-bm-min-hpps-128M-booti-busybox, but with the workaround
# for the slow execution in Zebu (by adding SEV instruction in ATF).

include $(CONF)/sys-preload-trch-bm-min-hpps-128M-booti-busybox/Makefile
include $(CONF)/lib-hpps-atf-sev/Makefile
